### Variables
@baseUrl = http://localhost:3000


###

# SignIn
# @name SignIn
POST {{baseUrl}}/signin

{
  "email": "mateusazevedo@gmail.com",
  "password": "12345678" 
}

###

# SignUp
# @name SignUp
POST {{baseUrl}}/signup

{
  "goal": "LOSE",
  "gender": "MALE",
  "birthDate": "1999-05-20",
  "height": 178,
  "weight": 94,
  "activityLevel": 5,
  "account": {
    "name": "Mateus",
    "email": "mateusazevedo@gmail.com",
    "password": "12345678"
  }
}

###

# Me
# @name GetMe

@token = {{SignIn.response.body.accessToken}}

GET {{baseUrl}}/me
Authorization: Bearer {{token}}


### Create Meal
# @name CreateMeal
POST {{baseUrl}}/meals
Authorization: Bearer {{token}}

{
  "fileType": "audio/m4a"
}