### Variables
@baseUrl = http://localhost:3000


###

# SignIn
# @name SignIn
POST https://7gx3j49sx2.execute-api.us-east-1.amazonaws.com/signin

{
  "email": "mateusazevedo@gmail.com",
  "password": "12345678" 
}

###

# SignUp
# @name SignUp
POST https://7gx3j49sx2.execute-api.us-east-1.amazonaws.com/signup

{
  "goal": "LOSE",
  "gender": "MALE",
  "birthDate": "1999-05-20",
  "height": 178,
  "weight": 94,
  "activityLevel": 5,
  "account": {
    "name": "José",
    "email": "ze@gmail.com",
    "password": "123123123"
  }
}

###

# Me
# @name GetMe

@token = 

GET {{baseUrl}}/me
Authorization: Bearer {{token}}


### Create Meal
# @name CreateMeal
POST {{baseUrl}}/meals
Authorization: Bearer {{token}}

{
  "fileType": "audio/m4a"
}

### List Meals

@queryParams = ?date=2025-07-19

# @name ListMeals
GET {{baseUrl}}/meals{{queryParams}}
Authorization: Bearer {{token}}

### Get Meal By Id

@mealId = f022bd3f-fedc-49fd-88c5-92a1d9fb66a3

GET {{baseUrl}}/meals/{{mealId}}
Authorization: Bearer {{token}}
