### Variables
@baseUrl = http://localhost:3000


###

# SignIn

POST {{baseUrl}}/signin

{
  "email": "mateuscorreiaazevedo@gmail.com",
  "password": "12345678" 
}

###

# SignUp

POST {{baseUrl}}/signup

{
  "goal": "LOSE",
  "gender": "MALE",
  "birthDate": "1999-05-20",
  "height": 180,
  "weight": 80,
  "activityLevel": 5,
  "account": {
    "name": "Mateus",
    "email": "mateus@gmail.com",
    "password": "12345678"
  }
}