org: personalmateus
service: foodiary-api

plugins:
  - serverless-offline

provider:
  name: aws
  region: us-east-1
  runtime: nodejs22.x
  architecture: arm64
  environment:
    DATABASE_URL: ${env:DATABASE_URL}
    JWT_SECRET: ${env:JWT_SECRET}
    BUCKET_NAME: !Ref UploadsBucket
    MEALS_QUEUE_URL: !Ref MealsQueue
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:PutObject
          # Resource: !GetAtt UploadsBucket.Arn
          Resource: !Sub '${UploadsBucket.Arn}/*'
        - Effect: Allow
          Action:
            - sqs:SendMessage
          Resource: !GetAtt MealsQueue.Arn
package:
  individually: true

build:
  esbuild:
   minify: true
   sourcemap: false

functions:
  health:
    handler: src/functions/health.handler
    events:
      - httpApi:
          path: /health
          method: GET

  signin:
    handler: src/functions/signin.handler
    events:
      - httpApi:
          path: /signin
          method: POST

  signup:
    handler: src/functions/signup.handler
    events:
      - httpApi:
          path: /signup
          method: POST

  createMeal:
    handler: src/functions/create-meal.handler
    events:
      - httpApi:
          path: /meals
          method: POST

  listMeals:
    handler: src/functions/list-meals.handler
    events:
      - httpApi:
          path: /meals
          method: GET
  
  getMealById:
    handler: src/functions/get-meal-by-id.handler
    events:
      - httpApi:
          path: /meals/{mealId}
          method: GET

  me:
    handler: src/functions/me.handler
    events:
      - httpApi:
          path: /me
          method: GET
  fileUploadedEvent:
    handler: src/functions/file-uploaded-event.handler
    events:
      - s3:
          bucket: !Ref UploadsBucket
          event: s3:ObjectCreated:*
          existing: true
          forceDeploy: true
  processMeal:
    handler: src/functions/process-meal.handler
    events:
      - sqs:
          arn: !GetAtt MealsQueue.Arn
          batchSize: 1

resources:
  Resources:
    UploadsBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: foodiary-bucket-app
    MealsQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: foodiary-meals-queue
        VisibilityTimeout: 60
        RedrivePolicy:
          maxReceiveCount: 1
          deadLetterTargetArn: !GetAtt MealsDLQ.Arn
    MealsDLQ:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: foodiary-meals-dlq